name: alpine-route-optimizer
region: nyc

services:
- name: web
  source_dir: alpine-route-optimizer
  github:
    repo: Sunsvea/legendary-guacamole
    branch: master
    deploy_on_push: true
  build_command: npm run build
  run_command: npm start
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
    type: GENERAL
  - key: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
    value: ${MAPBOX_TOKEN}
    type: SECRET